### ISSUE TITLE
Wrong OSGI dependency

### ISSUE THREAD

**Issue by bfarka** [Dynatrace/Dynatrace-AppMon-Docker-Monitor-Plugin#4]
in the Manifest you are depending on the dynatrace sdk bundle but you need to require the pdk bundle... since it is Plugin Development!

**Comment by Dynatrace-Asad-Ali** [comment]
You don't need the pdk bundle because when you run this plugin within DT env, it becomes available.

**Comment by Dynatrace-Asad-Ali** [comment]
Closing the issue since this plugin works in Dynatrace collector. All the required SDK and PDK files are made available automatically by the dynatrace server.

**Comment by centic9** [comment]
FYI, there is no separate "pdk" bundle in the Dynatrace OSGi bundles, all these classes are contained in the "sdk" bundle, hence the dependency on "sdk".
